import {
  THUMBNAIL_PREVIEW_HEIGHT,
  THUMBNAIL_PREVIEW_MIN_WIDTH,
  THUMBNAIL_PREVIEW_WIDTH
} from './thumbnail';

export const GRID_COLS_2 = 'grid grid-cols-2 gap-8 px-5 gap-y-4';

export const SEARCH_LECTURE_CARD = {
  CARD: `flex cursor-pointer w-full h-28 ${THUMBNAIL_PREVIEW_HEIGHT.MEDIUM} ${THUMBNAIL_PREVIEW_HEIGHT.LARGE}`,
  THUMBNAIL: `relative object-cover ${THUMBNAIL_PREVIEW_MIN_WIDTH.MEDIUM} ${THUMBNAIL_PREVIEW_MIN_WIDTH.LARGE} ${THUMBNAIL_PREVIEW_WIDTH.MEDIUM} ${THUMBNAIL_PREVIEW_WIDTH.LARGE}`,
} as const;
